// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: files/user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户信息
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NickName      string                 `protobuf:"bytes,2,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Mobile        string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Birthday      string                 `protobuf:"bytes,6,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Gender        uint32                 `protobuf:"varint,7,opt,name=gender,proto3" json:"gender,omitempty"`
	Role          uint32                 `protobuf:"varint,8,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_files_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_files_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_files_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UserInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserInfo) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *UserInfo) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserInfo) GetRole() uint32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *UserInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserInfo) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type UserLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLogin) Reset() {
	*x = UserLogin{}
	mi := &file_files_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogin) ProtoMessage() {}

func (x *UserLogin) ProtoReflect() protoreflect.Message {
	mi := &file_files_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogin.ProtoReflect.Descriptor instead.
func (*UserLogin) Descriptor() ([]byte, []int) {
	return file_files_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserLogin) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserLogin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserSearch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSearch) Reset() {
	*x = UserSearch{}
	mi := &file_files_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSearch) ProtoMessage() {}

func (x *UserSearch) ProtoReflect() protoreflect.Message {
	mi := &file_files_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSearch.ProtoReflect.Descriptor instead.
func (*UserSearch) Descriptor() ([]byte, []int) {
	return file_files_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserSearch) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserSearch) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

type UserListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNo        uint32                 `protobuf:"varint,1,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListReq) Reset() {
	*x = UserListReq{}
	mi := &file_files_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListReq) ProtoMessage() {}

func (x *UserListReq) ProtoReflect() protoreflect.Message {
	mi := &file_files_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListReq.ProtoReflect.Descriptor instead.
func (*UserListReq) Descriptor() ([]byte, []int) {
	return file_files_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserListReq) GetPageNo() uint32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *UserListReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*UserInfo            `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList) Reset() {
	*x = UserList{}
	mi := &file_files_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_files_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_files_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *UserList) GetData() []*UserInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_files_user_proto protoreflect.FileDescriptor

const file_files_user_proto_rawDesc = "" +
	"\n" +
	"\x10files/user.proto\x12\ruser.protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x03\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1b\n" +
	"\tnick_name\x18\x02 \x01(\tR\bnickName\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x1a\n" +
	"\bbirthday\x18\x06 \x01(\tR\bbirthday\x12\x16\n" +
	"\x06gender\x18\a \x01(\rR\x06gender\x12\x12\n" +
	"\x04role\x18\b \x01(\rR\x04role\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"?\n" +
	"\tUserLogin\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"=\n" +
	"\n" +
	"UserSearch\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\"C\n" +
	"\vUserListReq\x12\x17\n" +
	"\apage_no\x18\x01 \x01(\rR\x06pageNo\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\"M\n" +
	"\bUserList\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12+\n" +
	"\x04data\x18\x02 \x03(\v2\x17.user.protobuf.UserInfoR\x04data2\xcc\x02\n" +
	"\vUserService\x12>\n" +
	"\n" +
	"CreateUser\x12\x17.user.protobuf.UserInfo\x1a\x17.user.protobuf.UserInfo\x12:\n" +
	"\x05Login\x12\x18.user.protobuf.UserLogin\x1a\x17.user.protobuf.UserInfo\x12=\n" +
	"\aGetUser\x12\x19.user.protobuf.UserSearch\x1a\x17.user.protobuf.UserInfo\x12B\n" +
	"\vGetUserList\x12\x1a.user.protobuf.UserListReq\x1a\x17.user.protobuf.UserList\x12>\n" +
	"\n" +
	"UpdateUser\x12\x17.user.protobuf.UserInfo\x1a\x17.user.protobuf.UserInfoB\x05Z\x03pb/b\x06proto3"

var (
	file_files_user_proto_rawDescOnce sync.Once
	file_files_user_proto_rawDescData []byte
)

func file_files_user_proto_rawDescGZIP() []byte {
	file_files_user_proto_rawDescOnce.Do(func() {
		file_files_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_files_user_proto_rawDesc), len(file_files_user_proto_rawDesc)))
	})
	return file_files_user_proto_rawDescData
}

var file_files_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_files_user_proto_goTypes = []any{
	(*UserInfo)(nil),              // 0: user.protobuf.UserInfo
	(*UserLogin)(nil),             // 1: user.protobuf.UserLogin
	(*UserSearch)(nil),            // 2: user.protobuf.UserSearch
	(*UserListReq)(nil),           // 3: user.protobuf.UserListReq
	(*UserList)(nil),              // 4: user.protobuf.UserList
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_files_user_proto_depIdxs = []int32{
	5, // 0: user.protobuf.UserInfo.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: user.protobuf.UserInfo.updated_at:type_name -> google.protobuf.Timestamp
	5, // 2: user.protobuf.UserInfo.deleted_at:type_name -> google.protobuf.Timestamp
	0, // 3: user.protobuf.UserList.data:type_name -> user.protobuf.UserInfo
	0, // 4: user.protobuf.UserService.CreateUser:input_type -> user.protobuf.UserInfo
	1, // 5: user.protobuf.UserService.Login:input_type -> user.protobuf.UserLogin
	2, // 6: user.protobuf.UserService.GetUser:input_type -> user.protobuf.UserSearch
	3, // 7: user.protobuf.UserService.GetUserList:input_type -> user.protobuf.UserListReq
	0, // 8: user.protobuf.UserService.UpdateUser:input_type -> user.protobuf.UserInfo
	0, // 9: user.protobuf.UserService.CreateUser:output_type -> user.protobuf.UserInfo
	0, // 10: user.protobuf.UserService.Login:output_type -> user.protobuf.UserInfo
	0, // 11: user.protobuf.UserService.GetUser:output_type -> user.protobuf.UserInfo
	4, // 12: user.protobuf.UserService.GetUserList:output_type -> user.protobuf.UserList
	0, // 13: user.protobuf.UserService.UpdateUser:output_type -> user.protobuf.UserInfo
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_files_user_proto_init() }
func file_files_user_proto_init() {
	if File_files_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_files_user_proto_rawDesc), len(file_files_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_files_user_proto_goTypes,
		DependencyIndexes: file_files_user_proto_depIdxs,
		MessageInfos:      file_files_user_proto_msgTypes,
	}.Build()
	File_files_user_proto = out.File
	file_files_user_proto_goTypes = nil
	file_files_user_proto_depIdxs = nil
}
